/**
 * Open Decisions API
 * API for distributing data about decisions and people behind those decisions
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Attachment', 'model/Content'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Attachment'), require('./Content'));
  } else {
    // Browser globals (root is window)
    if (!root.PaatosApiClient) {
      root.PaatosApiClient = {};
    }
    root.PaatosApiClient.Action = factory(root.PaatosApiClient.ApiClient, root.PaatosApiClient.Attachment, root.PaatosApiClient.Content);
  }
}(this, function(ApiClient, Attachment, Content) {
  'use strict';




  /**
   * The Action model module.
   * @module model/Action
   * @version 0.0.7
   */

  /**
   * Constructs a new <code>Action</code>.
   * An action taken by a decision maker. Except for formalities (like quorum), these always involve a case and a decision by an organization or post, even if only postponing the decision. For decision making bodies, actions are always taken in context of a meeting. For officials, some cities also publish their decisions as being done in a meeting, although there is only one person present.
   * @alias module:model/Action
   * @class
   */
  var exports = function() {
    var _this = this;
















  };

  /**
   * Constructs a <code>Action</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Action} obj Optional instance to populate.
   * @return {module:model/Action} The populated <code>Action</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('data_source')) {
        obj['data_source'] = ApiClient.convertToType(data['data_source'], 'String');
      }
      if (data.hasOwnProperty('contents')) {
        obj['contents'] = ApiClient.convertToType(data['contents'], [Content]);
      }
      if (data.hasOwnProperty('attachments')) {
        obj['attachments'] = ApiClient.convertToType(data['attachments'], [Attachment]);
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
      }
      if (data.hasOwnProperty('modified_at')) {
        obj['modified_at'] = ApiClient.convertToType(data['modified_at'], 'Date');
      }
      if (data.hasOwnProperty('origin_id')) {
        obj['origin_id'] = ApiClient.convertToType(data['origin_id'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('ordering')) {
        obj['ordering'] = ApiClient.convertToType(data['ordering'], 'Number');
      }
      if (data.hasOwnProperty('article_number')) {
        obj['article_number'] = ApiClient.convertToType(data['article_number'], 'String');
      }
      if (data.hasOwnProperty('resolution')) {
        obj['resolution'] = ApiClient.convertToType(data['resolution'], 'String');
      }
      if (data.hasOwnProperty('case')) {
        obj['case'] = ApiClient.convertToType(data['case'], 'String');
      }
      if (data.hasOwnProperty('post')) {
        obj['post'] = ApiClient.convertToType(data['post'], 'String');
      }
      if (data.hasOwnProperty('event')) {
        obj['event'] = ApiClient.convertToType(data['event'], 'String');
      }
    }
    return obj;
  }

  /**
   * The action's url
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * The action's unique identifier
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The action's data source
   * @member {String} data_source
   */
  exports.prototype['data_source'] = undefined;
  /**
   * Array of contents
   * @member {Array.<module:model/Content>} contents
   */
  exports.prototype['contents'] = undefined;
  /**
   * Array of attachments
   * @member {Array.<module:model/Attachment>} attachments
   */
  exports.prototype['attachments'] = undefined;
  /**
   * The time at which the resource was created
   * @member {Date} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * The time at which the resource was last modified
   * @member {Date} modified_at
   */
  exports.prototype['modified_at'] = undefined;
  /**
   * The event's origin id
   * @member {String} origin_id
   */
  exports.prototype['origin_id'] = undefined;
  /**
   * Title of the action
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * Ordering of this action within a meeting (or possibly arbitrary ordering)
   * @member {Number} ordering
   */
  exports.prototype['ordering'] = undefined;
  /**
   * The article number given to this action after decision, will be null before decision
   * @member {String} article_number
   */
  exports.prototype['article_number'] = undefined;
  /**
   * Action's resolution
   * @member {String} resolution
   */
  exports.prototype['resolution'] = undefined;
  /**
   * Case url this action is related to
   * @member {String} case
   */
  exports.prototype['case'] = undefined;
  /**
   * Post url
   * @member {String} post
   */
  exports.prototype['post'] = undefined;
  /**
   * Event url this action is related to
   * @member {String} event
   */
  exports.prototype['event'] = undefined;



  return exports;
}));


