/**
 * Open Decisions API
 * API for distributing data about decisions and people behind those decisions
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PaatosApiClient) {
      root.PaatosApiClient = {};
    }
    root.PaatosApiClient.GeometryGeometry = factory(root.PaatosApiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GeometryGeometry model module.
   * @module model/GeometryGeometry
   * @version 0.0.7
   */

  /**
   * Constructs a new <code>GeometryGeometry</code>.
   * @alias module:model/GeometryGeometry
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>GeometryGeometry</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GeometryGeometry} obj Optional instance to populate.
   * @return {module:model/GeometryGeometry} The populated <code>GeometryGeometry</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('coordinates')) {
        obj['coordinates'] = ApiClient.convertToType(data['coordinates'], [Object]);
      }
    }
    return obj;
  }

  /**
   * Type
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * Array of GEO JSON coordinates
   * @member {Array.<Object>} coordinates
   */
  exports.prototype['coordinates'] = undefined;



  return exports;
}));


