/**
 * Open Decisions API
 * API for distributing data about decisions and people behind those decisions
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Area', 'model/Attachment', 'model/CaseRelatedCases', 'model/CaseSummary', 'model/CaseTitle'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Area'), require('./Attachment'), require('./CaseRelatedCases'), require('./CaseSummary'), require('./CaseTitle'));
  } else {
    // Browser globals (root is window)
    if (!root.PaatosApiClient) {
      root.PaatosApiClient = {};
    }
    root.PaatosApiClient.ModelCase = factory(root.PaatosApiClient.ApiClient, root.PaatosApiClient.Area, root.PaatosApiClient.Attachment, root.PaatosApiClient.CaseRelatedCases, root.PaatosApiClient.CaseSummary, root.PaatosApiClient.CaseTitle);
  }
}(this, function(ApiClient, Area, Attachment, CaseRelatedCases, CaseSummary, CaseTitle) {
  'use strict';




  /**
   * The ModelCase model module.
   * @module model/ModelCase
   * @version 0.0.3
   */

  /**
   * Constructs a new <code>ModelCase</code>.
   * A matter being decided withing the organization. These are often considered across multiple meetings and possibly across multiple decision makers. Cases can also be related to other cases, forming more complex structures. All that said, it is not unusual for a case to involve only a single action. Previous version used *issue* as similar concept, without interlinking.
   * @alias module:model/ModelCase
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>ModelCase</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelCase} obj Optional instance to populate.
   * @return {module:model/ModelCase} The populated <code>ModelCase</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('title')) {
        obj['title'] = CaseTitle.constructFromObject(data['title']);
      }
      if (data.hasOwnProperty('summary')) {
        obj['summary'] = CaseSummary.constructFromObject(data['summary']);
      }
      if (data.hasOwnProperty('attachments')) {
        obj['attachments'] = ApiClient.convertToType(data['attachments'], [Attachment]);
      }
      if (data.hasOwnProperty('category')) {
        obj['category'] = ApiClient.convertToType(data['category'], 'String');
      }
      if (data.hasOwnProperty('area')) {
        obj['area'] = ApiClient.convertToType(data['area'], [Area]);
      }
      if (data.hasOwnProperty('district')) {
        obj['district'] = ApiClient.convertToType(data['district'], 'String');
      }
      if (data.hasOwnProperty('category_id')) {
        obj['category_id'] = ApiClient.convertToType(data['category_id'], 'String');
      }
      if (data.hasOwnProperty('related_cases')) {
        obj['related_cases'] = ApiClient.convertToType(data['related_cases'], [CaseRelatedCases]);
      }
      if (data.hasOwnProperty('originator')) {
        obj['originator'] = ApiClient.convertToType(data['originator'], 'String');
      }
      if (data.hasOwnProperty('creation_date')) {
        obj['creation_date'] = ApiClient.convertToType(data['creation_date'], 'Date');
      }
      if (data.hasOwnProperty('public')) {
        obj['public'] = ApiClient.convertToType(data['public'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/CaseTitle} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {module:model/CaseSummary} summary
   */
  exports.prototype['summary'] = undefined;
  /**
   * Attachments related to this case
   * @member {Array.<module:model/Attachment>} attachments
   */
  exports.prototype['attachments'] = undefined;
  /**
   * Category this case belongs to (\"tehtäväluokka\")
   * @member {String} category
   */
  exports.prototype['category'] = undefined;
  /**
   * Geographic areas this case is related to
   * @member {Array.<module:model/Area>} area
   */
  exports.prototype['area'] = undefined;
  /**
   * Name of district (if any), that this issue is related to.
   * @member {String} district
   */
  exports.prototype['district'] = undefined;
  /**
   * Identifier code for the category, if applicable. In finland this could be the national \"Tehtäväluokitus\"
   * @member {String} category_id
   */
  exports.prototype['category_id'] = undefined;
  /**
   * Other cases that are related to this case
   * @member {Array.<module:model/CaseRelatedCases>} related_cases
   */
  exports.prototype['related_cases'] = undefined;
  /**
   * Person or organization the proposed this case to the city
   * @member {String} originator
   */
  exports.prototype['originator'] = undefined;
  /**
   * Date this case was entered into system
   * @member {Date} creation_date
   */
  exports.prototype['creation_date'] = undefined;
  /**
   * Is this case public?
   * @member {Boolean} public
   */
  exports.prototype['public'] = undefined;



  return exports;
}));


