/**
 * Open Decisions API
 * API for distributing data about decisions and people behind those decisions
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PaatosApiClient) {
      root.PaatosApiClient = {};
    }
    root.PaatosApiClient.Organization = factory(root.PaatosApiClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Organization model module.
   * @module model/Organization
   * @version 0.0.7
   */

  /**
   * Constructs a new <code>Organization</code>.
   * A group with a common purpose or reason for existence that goes beyond the set of people belonging to it
   * @alias module:model/Organization
   * @class
   */
  var exports = function() {
    var _this = this;














  };

  /**
   * Constructs a <code>Organization</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Organization} obj Optional instance to populate.
   * @return {module:model/Organization} The populated <code>Organization</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('data_source')) {
        obj['data_source'] = ApiClient.convertToType(data['data_source'], 'String');
      }
      if (data.hasOwnProperty('events')) {
        obj['events'] = ApiClient.convertToType(data['events'], ['String']);
      }
      if (data.hasOwnProperty('posts')) {
        obj['posts'] = ApiClient.convertToType(data['posts'], ['String']);
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
      }
      if (data.hasOwnProperty('modified_at')) {
        obj['modified_at'] = ApiClient.convertToType(data['modified_at'], 'Date');
      }
      if (data.hasOwnProperty('origin_id')) {
        obj['origin_id'] = ApiClient.convertToType(data['origin_id'], 'String');
      }
      if (data.hasOwnProperty('classification')) {
        obj['classification'] = ApiClient.convertToType(data['classification'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('founding_date')) {
        obj['founding_date'] = ApiClient.convertToType(data['founding_date'], 'Date');
      }
      if (data.hasOwnProperty('dissolution_date')) {
        obj['dissolution_date'] = ApiClient.convertToType(data['dissolution_date'], 'Date');
      }
      if (data.hasOwnProperty('parent')) {
        obj['parent'] = ApiClient.convertToType(data['parent'], 'String');
      }
    }
    return obj;
  }

  /**
   * The organization's url
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * The organization's unique identifier
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The organization's data source
   * @member {String} data_source
   */
  exports.prototype['data_source'] = undefined;
  /**
   * The organization's events
   * @member {Array.<String>} events
   */
  exports.prototype['events'] = undefined;
  /**
   * The organization's posts
   * @member {Array.<String>} posts
   */
  exports.prototype['posts'] = undefined;
  /**
   * The time at which the resource was created
   * @member {Date} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * The time at which the resource was last modified
   * @member {Date} modified_at
   */
  exports.prototype['modified_at'] = undefined;
  /**
   * The organization's origin id
   * @member {String} origin_id
   */
  exports.prototype['origin_id'] = undefined;
  /**
   * The organization's classification
   * @member {String} classification
   */
  exports.prototype['classification'] = undefined;
  /**
   * The organization's name
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * The time at which the organization was founded
   * @member {Date} founding_date
   */
  exports.prototype['founding_date'] = undefined;
  /**
   * The time at which the organization was dissolved
   * @member {Date} dissolution_date
   */
  exports.prototype['dissolution_date'] = undefined;
  /**
   * The url of the organization's parent organization
   * @member {String} parent
   */
  exports.prototype['parent'] = undefined;



  return exports;
}));


