/**
 * Open Decisions API
 * API for distributing data about decisions and people behind those decisions
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.6aikaPaatosClient);
  }
}(this, function(expect, 6aikaPaatosClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new 6aikaPaatosClient.Action();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Action', function() {
    it('should create an instance of Action', function() {
      // uncomment below and update the code to test Action
      //var instane = new 6aikaPaatosClient.Action();
      //expect(instance).to.be.a(6aikaPaatosClient.Action);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new 6aikaPaatosClient.Action();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new 6aikaPaatosClient.Action();
      //expect(instance).to.be();
    });

    it('should have the property _case (base name: "case")', function() {
      // uncomment below and update the code to test the property _case
      //var instane = new 6aikaPaatosClient.Action();
      //expect(instance).to.be();
    });

    it('should have the property ordering (base name: "ordering")', function() {
      // uncomment below and update the code to test the property ordering
      //var instane = new 6aikaPaatosClient.Action();
      //expect(instance).to.be();
    });

    it('should have the property articleNumber (base name: "article_number")', function() {
      // uncomment below and update the code to test the property articleNumber
      //var instane = new 6aikaPaatosClient.Action();
      //expect(instance).to.be();
    });

    it('should have the property responsibleParty (base name: "responsible_party")', function() {
      // uncomment below and update the code to test the property responsibleParty
      //var instane = new 6aikaPaatosClient.Action();
      //expect(instance).to.be();
    });

    it('should have the property delegatePost (base name: "delegate_post")', function() {
      // uncomment below and update the code to test the property delegatePost
      //var instane = new 6aikaPaatosClient.Action();
      //expect(instance).to.be();
    });

    it('should have the property content (base name: "content")', function() {
      // uncomment below and update the code to test the property content
      //var instane = new 6aikaPaatosClient.Action();
      //expect(instance).to.be();
    });

    it('should have the property votes (base name: "votes")', function() {
      // uncomment below and update the code to test the property votes
      //var instane = new 6aikaPaatosClient.Action();
      //expect(instance).to.be();
    });

  });

}));
