/**
 * Open Decisions API
 * API for distributing data about decisions and people behind those decisions
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.6aikaPaatosClient);
  }
}(this, function(expect, 6aikaPaatosClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new 6aikaPaatosClient.CaseRelatedCases();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CaseRelatedCases', function() {
    it('should create an instance of CaseRelatedCases', function() {
      // uncomment below and update the code to test CaseRelatedCases
      //var instane = new 6aikaPaatosClient.CaseRelatedCases();
      //expect(instance).to.be.a(6aikaPaatosClient.CaseRelatedCases);
    });

    it('should have the property _case (base name: "case")', function() {
      // uncomment below and update the code to test the property _case
      //var instane = new 6aikaPaatosClient.CaseRelatedCases();
      //expect(instance).to.be();
    });

    it('should have the property relationType (base name: "relation_type")', function() {
      // uncomment below and update the code to test the property relationType
      //var instane = new 6aikaPaatosClient.CaseRelatedCases();
      //expect(instance).to.be();
    });

  });

}));
