/**
 * Open Decisions API
 * API for distributing data about decisions and people behind those decisions
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.6aikaPaatosClient);
  }
}(this, function(expect, 6aikaPaatosClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new 6aikaPaatosClient.Organization();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Organization', function() {
    it('should create an instance of Organization', function() {
      // uncomment below and update the code to test Organization
      //var instane = new 6aikaPaatosClient.Organization();
      //expect(instance).to.be.a(6aikaPaatosClient.Organization);
    });

    it('should have the property parent (base name: "parent")', function() {
      // uncomment below and update the code to test the property parent
      //var instane = new 6aikaPaatosClient.Organization();
      //expect(instance).to.be();
    });

    it('should have the property area (base name: "area")', function() {
      // uncomment below and update the code to test the property area
      //var instane = new 6aikaPaatosClient.Organization();
      //expect(instance).to.be();
    });

    it('should have the property memberships (base name: "memberships")', function() {
      // uncomment below and update the code to test the property memberships
      //var instane = new 6aikaPaatosClient.Organization();
      //expect(instance).to.be();
    });

    it('should have the property posts (base name: "posts")', function() {
      // uncomment below and update the code to test the property posts
      //var instane = new 6aikaPaatosClient.Organization();
      //expect(instance).to.be();
    });

    it('should have the property voteEvents (base name: "vote_events")', function() {
      // uncomment below and update the code to test the property voteEvents
      //var instane = new 6aikaPaatosClient.Organization();
      //expect(instance).to.be();
    });

    it('should have the property children (base name: "children")', function() {
      // uncomment below and update the code to test the property children
      //var instane = new 6aikaPaatosClient.Organization();
      //expect(instance).to.be();
    });

  });

}));
