/**
 * Open Decisions API
 * API for distributing data about decisions and people behind those decisions
 *
 * OpenAPI spec version: 0.0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.6aikaPaatosClient);
  }
}(this, function(expect, 6aikaPaatosClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new 6aikaPaatosClient.CasesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CasesApi', function() {
    describe('actionsList', function() {
      it('should call actionsList successfully', function(done) {
        //uncomment below and update the code to test actionsList
        //instance.actionsList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('actionsRetrieve', function() {
      it('should call actionsRetrieve successfully', function(done) {
        //uncomment below and update the code to test actionsRetrieve
        //instance.actionsRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesList', function() {
      it('should call casesList successfully', function(done) {
        //uncomment below and update the code to test casesList
        //instance.casesList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('videoDetail', function() {
      it('should call videoDetail successfully', function(done) {
        //uncomment below and update the code to test videoDetail
        //instance.videoDetail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
